/**
 *
 */
package com.ltu.sdk.camera;

import android.graphics.Bitmap;

/**
 * Used when a {@link Bitmap} cannot be decoded from a byte array
 *
 */
public class BitmapDecodingException extends Exception {

    /**
     * Required for serialization - auto generated by IDE
     */
    private static final long serialVersionUID = -4981911563564141943L;


    public BitmapDecodingException() {
        super("Cannot decode Bitmap from byte array");
    }
}
