/**
 *
 */
package com.ltu.sdk.camera;

/**
 * Used when the preview image format can't be handled
 */
public class PreviewImageFormatException extends Exception {

    /**
     * Required for serialization - auto generated by IDE
     */
    private static final long serialVersionUID = -3348926849234645575L;

    public PreviewImageFormatException(String message) {
        super(message);
    }

}
